kind: Deployment
apiVersion: apps/v1
metadata:
  name: emailapikube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emailapikube
  template:
    metadata:
      labels:
        app: emailapikube
    spec:
      containers:
        - name: emailapikube
          image: rsankarb/springboot-emailapi:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: emailapikube
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      nodePort: 31002
  selector:
    app: emailapikube